"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

from dotenv import load_dotenv, find_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# Automatically find and load the .env file
load_dotenv(find_dotenv())

BREVO_API_KEY = os.getenv("BREVO_API_KEY", "").strip()

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-gjf=jcvrz3n8ca+(u$^d%61557!&3d=z*m6ac^@z=3cn&*vt*d'
SECRET_KEY = os.getenv("SECRET_KEY")

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = os.getenv("DEBUG", "False").lower() == "true"
IS_PRODUCTION = not DEBUG

# # Application definition
INSTALLED_APPS = [
    'daphne',
    'channels',
    'corsheaders',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',
    'house',
    'inventory',
    'notifications',
    'rest_framework',
]

AUTH_USER_MODEL = 'accounts.CustomUser'  # Swap main User model for Custom User model

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# added for notification (channels)
ASGI_APPLICATION = 'backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Fetch the environment variable dynamically
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

if DATABASE_URL:
    # Handles BOTH Render Internal and Render External URLs automatically
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True 
        )
    }
else:
    # Fallback to local development database if DATABASE_URL is missing
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Static files (WhiteNoise)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework defaults
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework.authentication.SessionAuthentication',
    ]
}

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = True

CORS_EXPOSE_HEADERS = [
    "Content-Type",
    "X-CSRFToken",
]

# ==================================================
# ENVIRONMENT BASED CONFIGURATION
# ==================================================

if IS_PRODUCTION:
    FRONTEND_URL = "https://n-inventory.com"

    ALLOWED_HOSTS = [
        "api.n-inventory.com",
        "n-inventory.com", 
        ".up.railway.app",
    ]

    # CSRF_COOKIE_DOMAIN = ".n-inventory.com"
    # SESSION_COOKIE_DOMAIN = ".n-inventory.com"

    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

    # Cookies Security Settings
    CSRF_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

    # Origins
    CORS_ALLOWED_ORIGINS = [
        "https://n-inventory.com",
        "https://www.n-inventory.com",
        "http://localhost",          # Android Standard
        "https://localhost",         # Android Secure (Capacitor Secure Context)
        "capacitor://localhost",     # iOS Standard
    ]

    CSRF_TRUSTED_ORIGINS = [
        "https://n-inventory.com",
        "https://www.n-inventory.com",
        "http://localhost",          # Android Capacitor Client
        "https://localhost",
        "capacitor://localhost",     # iOS Capacitor Client
    ]

else:
    FRONTEND_URL = "http://localhost:5173"

    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
    ]

    # Remove cookie domains for localhost
    CSRF_COOKIE_DOMAIN = None
    SESSION_COOKIE_DOMAIN = None

    USE_X_FORWARDED_HOST = False

    # Cookies Development Settings
    CSRF_COOKIE_SAMESITE = None
    SESSION_COOKIE_SAMESITE = None
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False

    # Origins
    CORS_ALLOWED_ORIGINS = [
        "http://127.0.0.1:5173",
        "http://localhost:5173",
        "http://localhost",          # Android Capacitor local testing
        "capacitor://localhost",     # iOS Capacitor local testing
    ]

    CSRF_TRUSTED_ORIGINS = [
        "http://127.0.0.1:5173",
        "http://localhost:5173",
        "http://localhost",          # Android Capacitor local testing
        "capacitor://localhost",     # iOS Capacitor local testing
    ]
    