# Generated by Django 6.0 on 2026-06-09 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='house.house')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('barcode', models.CharField(max_length=20, null=True, unique=True)),
                ('description', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('min_limit', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.category')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='house.house')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'house'), name='unique_category_per_house', violation_error_message='Category already exists in this house'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('house', 'barcode'), name='unique_item_per_house'),
        ),
    ]
